apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: transition-operator-system
type: Opaque
stringData:
  GIT_SERVER_URL: "http://47.129.115.173:31413"
  GIT_SECRET_NAME: "git-user-secret"
  GIT_SECRET_NAMESPACE: "default"