apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: transition-operator-system
type: Opaque
stringData:
  MINIO_ENDPOINT: "47.129.115.173:31092"
  MINIO_ACCESS_KEY: "nephio1234"
  MINIO_SECRET_KEY: "secret1234"
  MINIO_BUCKET: "checkpoints"