apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: transition-operator-system
type: Opaque
stringData:
  REPOSITORY: "vitu1"
  SECRET_NAME_REF: "reg-credentials"
  SECRET_NAMESPACE_REF: "default"
  REGISTRY_URL: "docker.io"
  REGISTRY_PASSWORD: "PUT_PASSWORD_HERE"